blog/urls.py
from django.conf.urls import url

from . import views

# My creation   ——定义blog应用的url模式


app_name = 'blog'   # <URL模式命名空间>：告诉Django该urls.py模块属于blog应用
'''
一个复杂的 Django 项目可能不止这些URL模式，例如一些第三方应用中也可能有叫 index、detail 的URL模式
要把它们区分开来防止冲突需要通过 app_name 来指定命名空间
'''
urlpatterns = [  # 定义网址和视图函数的关系
    url(r'^$', views.IndexView.as_view(), name='index'),  # 绑定主页URL，参数1是网址，参数2是视图函数，参数3是处理函数的别名
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),    # 绑定详情页URL
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),

]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 将手动创建的urls.py包含进来
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),

    # RSS 的 URL 模式
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),

    # 搜索的 URL 模式
    url(r'^search/', include('haystack.urls')),
]

comments/urls.py
from django.conf.urls import url

from . import views

# My creation   ——定义评论应用的url模式


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
import markdown
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
from django.contrib.auth.models import User

# Create your models here.  ——创建文章数据表


class Category(models.Model):
    """数据表：Category（分类）—— 数据列：name
    Django 要求模型必须继承 models.Model 类
    Category 只需要一个列 name 即可
    CharField 指定了列 name 的数据类型为字符型，最大长度为100
    Django 全部内置类型查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100, verbose_name='分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = "分类"


class Tag(models.Model):
    """数据表：Tag（标签）—— 数据列：name"""
    name = models.CharField(max_length=100, verbose_name='标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"


class Post(models.Model):
    """数据表：Post（文章）
       数据列：title —— 文章标题
              body —— 文章正文
              created_time —— 文章的创建时间
              modified_time —— 文章最后修改时间
              excerpt —— 文章摘要
              views —— 阅读量
            category —— 将 Category（分类）数据表与 Post（文章）数据表进行关联（一对多）
            tags —— 将 Tag（标签）数据表与 Post（文章）数据表进行关联（多对多）
            author —— 文章作者（一对多）
    """
    title = models.CharField(max_length=60, verbose_name='标题')

    # 使用字段TextField存储大段文本
    body = models.TextField(verbose_name='正文')

    '''文章摘要（可选）；
    默认情况下字段CharField要求必须存入数据，指定其参数blank=True即可允许空值'''
    excerpt = models.CharField(max_length=20, blank=True, verbose_name='摘要')

    # 使用字段DateTimeField存储时间
    created_time = models.DateTimeField(verbose_name='建立时间')
    modified_time = models.DateTimeField(verbose_name='最后修改时间')

    '''新增 views 字段记录阅读量：该类型值只能为0或正整数，初始化为0'''
    views = models.PositiveIntegerField(default=0, verbose_name='阅读量')

    '''规定一篇文章只能对应一个分类，但一个分类下可以有多篇文章，所以使用ForeignKey（一对多）的关联关系
    规定一篇文章可以有多个标签，一个标签下也可能有多篇文章，所以使用ManyToManyField（多对多）关联关系
    规定文章可以没有标签，因此为标签Tag指定blank=True'''
    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')

    ''' User 从django.contrib.auth.models导入
    django.contrib.auth 是Django内置应用，专门处理网站用户的注册，登录等流程，User是其内置的用户模型
    通过ForeignKey一对多的将作者 User 和 Post 文章关联起来'''
    author = models.ForeignKey(User, verbose_name='作者')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """屏蔽域名，生成纯净的URL
        :return: reverse()
        参数1意为blog应用下的 name=detail 的函数
        由于 app_name = 'blog' 告诉了 Django urls.py 模块属于 blog 应用
        Django 能够顺利找到 blog 应用下 name 为 detail 的视图函数
        于是 reverse 函数会去解析这个视图函数对应的 URL
        这里 detail 对应的规则就是 post/(?P<pk>[0-9]+)/ 这个正则表达式
        而正则表达式部分会被后面传入的参数 pk 替换
        所以，如果 Post 的 id（或 pk，这里 pk 和 id 是等价的） 是 255 的话
        那么 get_absolute_url 函数返回的就是 /post/255/ ，这样 Post 就生成了自己的 URL
        """
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        """ increase_views 方法首先将自身对应的 views 字段值 +1
        然后将变化更新到数据库，使用 update_fields 参数指定只更新 views字段来提高效率"""
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        """如果没有填写文章摘要则自动生成，调用此方法前写的文章不生效"""
        if not self.excerpt:
            # 将 body 中的 Markdown 文本转为 HTML 文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 去掉 HTML 文本里的 HTML 标签，取前26个字符作为摘要
            self.excerpt = strip_tags(md.convert(self.body))[:2]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        """ Django 允许在models.Model的子类里定义一个Meta内部类
        这个内部类通过指定一些属性来规定这个类该有的一些特性，例如 Post 的排序方式
        """
        ''' ordering 属性用来指定文章排序方式
        ['-created_time'] 指定按照文章发布时间排序，且负号表示逆序排列
        列表中可以用多个项：比如 ordering = ['-created_time', 'title']：
            那么首先依据 created_time 排序，如果 created_time 相同，则再依据 title 排序
            这样指定以后所有返回的文章列表都会自动按照 Meta 中指定的顺序排序'''
        verbose_name = "文章"
        verbose_name_plural = "文章"
        ordering = ['-created_time', 'title']

comments/models.py
from django.db import models

# Create your models here.  ——创建comments应用的数据表


class Comment(models.Model):
    """数据表：Comment（评论）
       数据列：name —— 评论者名
              email —— 邮箱
              url —— 个人网址
              text —— 评论内容
              created_time —— 评论时间    auto_now_add=True 参数自动填充当前时间
            post —— 将 Post（文章）数据表与 Comment（评论）数据表进行关联（一对多）
    """
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
import markdown
from django.db.models import Q
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from .models import Post, Category, Tag
from comments.forms import CommentForm

# Create your views here.   ——定义视图函数


def search(request):
    """搜索功能视图函数"""

    '''获得用户提交的搜索关键词
    用户通过表单 get 方法提交的数据 Django 保存在 request.GET 里
    这是个类似于Py字典的对象，所以使用 get 方法从中取出键 q 对应的值，即用户的搜索关键词
    至于字典的键之所以叫 q 是因为模板的表单中搜索框 input 的 name 属性的值是 q '''
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        '''校验，如果用户没有输入搜索关键词而提交了表单
        就无需执行查询而在模板中渲染一个错误提示信息'''
        error_msg = '未输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    '''用户输入了搜索关键词就通过 filter 方法从数据库里过滤出符合条件的所有文章
    这里的过滤条件是 title__icontains=q，即 title 中包含（contains）关键字 q
    前缀 i 表示不区分大小写， icontains 是查询表达式（Field lookups）'''
    # Q 对象用于包装查询表达式，其作用是为了提供复杂的查询逻辑
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})


class IndexView(ListView):
    """主页的类视图
    类视图：因为 IndexView 类功能是从数据库中获取文章列表
    ListView 可以从数据库获取某个模型列表数据，所以继承 ListView
    属性：
        model：指定要获取的模型是 Post
        context_object_name：指定获取的模型列表数据保存的变量名，这个变量会被传递给模板
        template_name：指定要用这个视图渲染的模板
    """
    model = Post
    context_object_name = 'post_list'
    template_name = 'blog/index.html'

    # 指定 paginate_by 属性以开启分页功能，其值为每页文章数
    paginate_by = 3

    def get_context_data(self, **kwargs):
        """函数 render 的 context 参数将视图函数中的模板变量作为一个字典传递给模板
        例如 render(request, 'blog/index.html', context={'post_list': post_list})
        传递了一个 {'post_list': post_list} 字典给模板
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的
        所以复写该方法，以便插入一些自定义的模板变量"""
        # 首先获得父类生成的传递给模板的字典
        context = super().get_context_data(**kwargs)

        '''父类生成的字典中已有 paginator、page_obj、is_paginated 三个模板变量
        paginator 是 Paginator 的一个实例
        page_obj 是 Page 的一个实例
        is_paginated 是一个布尔变量，用于指示是否已分页
            例如如果规定每页10个数据，而本身只有5个数据，其实就用不着分页
            此时 is_paginated = False '''
        #  context 是一个字典，调用 get 方法从中取出某个键对应的值
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        '''将分页导航条的模板变量更新到 context 中
        pagination_data 方法返回的也是一个字典'''
        context.update(pagination_data)

        '''将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量渲染模板
        此时 context 字典中已有了显示分页导航条所需的数据'''
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，就不显示分页导航，因此返回一个空字典
            return {}

        # 当前页左/右的页码，初始为0
        left = []
        right = []

        # 标示第1页/最后1页后/前是否需要显示省略号
        left_has_more = False
        right_has_more = False

        '''标示是否需要显示第1页/末页的页码
        若当前页左边/右面的连续页码中已经含有第1页/末页的页码，此时无需再显示第1页/末页的页码
        其它情况下第1页/末页的页码始终需要显示
        初始值为 False'''
        first = False
        last = False

        # 获得当前用户请求的页码
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，如分了2页，就是[1, 2, 3]
        page_range = paginator.page_range

        if page_number == 1:
            '''如果用户请求第一页的数据，那么当前页左边不需要数据
            因此 left=[]（已默认为空）
            此时只要获取当前页右边的连续页码号
            比如页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]
            这里只获取了当前页码后连续两个页码，可以更改这个数字以获取更多页码'''
            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages - 1:
                '''如果最右边的页码比最后一页的页码减去 1 还小
                说明最右边的页码和最后一页的页码之间还有其它页码
                因此需要显示省略号，通过 right_has_more 来指示'''
                right_has_more = True

            if right[-1] < total_pages:
                '''如果最右边的页码比最后一页的页码号小
                说明当前页右边的连续页码号中不包含最后一页的页码
                所以需要显示最后一页的页码号，通过 last 来指示'''
                last = True

        elif page_number == total_pages:
            '''如果用户请求最后1页的数据，当前页右边不需要数据，因此 right=[]（已默认为空），
            此时只要获取当前页左边的连续页码
            比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            这里只获取了当前页码后连续2个页码，更改这个数字以获取更多页码'''
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            '''如果最左边的页码比第2页页码还大
            说明最左边的页码和第1页的页码之间还有其它页码，因此需要显示省略号
            通过 left_has_more 来指示'''
            if left[0] > 2:
                left_has_more = True

            '''如果最左边的页码比第1页的页码大，说明当前页左边连续页码号中不包含第一页
            所以需要显示第一页的页码，通过 first 来指示'''
            if left[0] > 1:
                first = True

        else:
            '''用户请求的既不是最后1页，也不是第1页，则需要获取当前页左右两边的连续页码
            这里只获取了当前页码前后连续2个页码，更改这个数字以获取更多页码'''
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后1页及其前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第1页及其后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class PostDetailView(DetailView):
    """详情页的类视图"""
    model = Post
    context_object_name = 'post'
    template_name = 'blog/detail.html'

    def get(self, request, *args, **kwargs):
        """覆写 get 方法，每当文章被访问一次，就将文章阅读量 +1
        get 方法返回的是一个 HttpResponse 实例
        只有当 get 方法被调用后，才有 self.object 属性
        其值为 Post 模型实例，即被访问的文章 post"""
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 文章阅读量 +1，self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        """对 post 的 body 值进行渲染"""
        post = super(PostDetailView, self).get_object(queryset=None)
        # 对md语法的拓展
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',  # 多种拓展
            'markdown.extensions.codehilite',  # 语法高亮拓展
            # 'markdown.extensions.toc',  # 自动生成目录拓展
            TocExtension(slugify=slugify)
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        """将 post、评论表单、post 下的评论列表传递给模板"""
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


class ArchivesView(ListView):
    """归档的类视图"""
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month
                                                               )


class CategoryView(ListView):
    """分类的类视图，因为属性和类 IndexView 一样，所以直接继承 IndexView """
    model = Post
    context_object_name = 'post_list'
    template_name = 'blog/index.html'

    def get_queryset(self):
        """获取指定分类下的文章列表数据：
        覆写了父类的 get_queryset 方法，该方法默认获取指定模型的全部列表数据"""
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(ListView):
    """标签的类视图"""
    model = Post
    context_object_name = 'post_list'
    template_name = 'blog/index.html'

    def get_queryset(self):
        """获取指定标签下的文章列表数据"""
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


# def index(request):
#     """主页视图
#     :param request: HTTP请求
#     :return: render: 根据参数构造HttpResponse
#     """
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})


# def archives(request, year, month):
#     """归档视图
#     类似主页视图，但不再使用all()获取全部文章，而是使用filter根据条件筛选
#     Py 中类实例调用属性的方法通常是 created_time.year，但是由于这里作为函数的参数列表
#     所以 Django 要求把点替换成两个下划线，即 created_time__year 和 created_time__month
#     """
#     post_list = Post.objects.filter(created_time__year=year,
#                                     created_time__month=month,).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})


# def category(request, pk):
#     """分类视图"""
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})


# def detail(request, pk):
#     """详情页视图
#     根据从URL捕获的文章id（即pk，这里pk和id等价）获取数据库中文章id为pk的记录，然后传递给模板
#     当传入的pk对应的Post在数据库中存在时，get_object_or_404方法返回对应的post，不存在则返回404
#     :param request:
#     :param pk:
#     :return:
#     """
#     post = get_object_or_404(Post, pk=pk)
#
#     # 调用模型方法ncrease_views() +1 阅读量
#     post.increase_views()
#
#     post.body = markdown.markdown(post.body,
#                                   extensions=[  # 对md语法的拓展
#                                       'markdown.extensions.extra',  # 多种拓展

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}    <!-- safe标签（过滤器Filter）：告诉Django该段文本安全 -->
            <br>
            <div class="widget-tag-cloud">
                <ul>
                    标签：
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </article>
    <section class="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字:</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱:</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址:</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12" id="col-md-axb">
                    <label for="{{ form.text.id_for_label }}">评论:</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>

        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date">{{ comment.created_time }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>

{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
    <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
                    </span>
                    <span class="post-date">
                        <a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a>
                    </span>
                    <span class="post-author">
                        <a href="#">{{ post.author }}</a>
                    </span>
                    <span class="comments-link">
                        <a href="{{ post.get_absolute_url }}#comment">{{ post.comment_set.count }} 评论</a>
                    </span>
                    <span class="views-count">
                        <a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a>
                    </span>
                </div>
            </header>

            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}...</p>
                <!-- 自动摘要显示的第二种方法（会导致摘要里可能含有块级HTML，不推荐）：<p>{{ post.excerpt|truncatechars:26 }}...</p> -->
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">阅读文章</a><!-- <span class="meta-nav">→</span> -->
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂无文章</div>
    {% endfor %}
    <!-- 简单分页效果 -->

    <!-- {% if is_paginated %}
    <div class="pagination-simple"> -->
        <!-- 如果当前页面有上一页，显示上一页按钮 -->
        <!-- {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">&lt;上一页&gt;</a>
        {% endif %} -->
        <!-- 显示当前页面信息 -->
        <!-- <span class="current">{{ page_obj.number }} | {{ paginator.num_pages }}</span> -->
        <!-- 若当前当前页还有下一页，现实下一页按钮 -->
        <!-- {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">&lt;下一页&gt;</a>
        {% endif %}
    </div>
    {% endif %} -->
   
    <!-- 进阶分页效果 -->
    {% if is_paginated %}
    <div class="pagination" id="center">
        <span>| </span>
        {% if first %}
            <a href="?page=1">1 | </a>
        {% endif %}
        {% if left %}
            {% if left_has_more %}
                <span>... | </span>
            {% endif %}
            {% for i in left %}
                <a href="?page={{ i }}">{{ i }} | </a>
            {% endfor %}
        {% endif %}
            <a href="?page={{ page_obj.number }}" style="color: #00D1A5">
                {{ page_obj.number }}
            </a><span> | </span>
        {% if right %}
            {% for i in right %}
                <a href="?page={{ i }}">{{ i }} | </a>
            {% endfor %}
            {% if right_has_more %}
                <span>... | </span>
            {% endif %}
        {% endif %}
        {% if last %}
            <a href="?page={{ paginator.num_pages }}">
                {{ paginator.num_pages }} | 
            </a>
        {% endif %}
    </div>
    {% endif %}

{% endblock main %}

templates/blog/new_post.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <a href="{% url 'yj_logs:topic' topic.id %}">{{ topic }}</a>
    </h3>
{% endblock header %}

{% block content %}

    <h4>新文章：</h4>

    <form method="post" action="{% url 'blog:new_entry' topic.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">完成</button>
        {% endbuttons %}
    </form>

{% endblock content %}